[package]
authors = ["Sergey Parilin <parilinsa@gmail.com>"]
edition = "2018"
name = "asdl-rs"
version = "0.1.0"

[dependencies]
m_lexer = "0.0.4"
rowan = "0.5.0"
rustc-hash = "1.0.1"
serde = { version = "1.0.91", features = ["derive"]}

[dev-dependencies]
insta = "0.8.1"
