[package]
authors = ["Sergey Parilin <parilinsa@gmail.com>"]
edition = "2018"
name = "asdl"
version = "0.1.0"

[dependencies]
rustc-hash = "1.0.1"

[dependencies.nom]
version = "5"
default-features = false
features = ["std"]

[dev-dependencies]
insta = "0.8.1"