[package]
authors = ["Sergey Parilin <parilinsa@gmail.com>"]
edition = "2018"
name = "asdl_tera"
version = "0.1.0"

[dependencies]
asdl = { path = "../asdl" }
clap = "2.33.0"
heck = "0.3.1"
tera = "0.11.20"